//
//  Announcements.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.10
//

import Foundation
import UIKit
import AWSDynamoDB

class Announcements: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _creationDate: NSNumber?
    var _announcementId: String?
    var _category: String?
    var _content: String?
    var _keywords: Set<String>?
    var _title: String?
    
    class func dynamoDBTableName() -> String {

        return "joyfulchurch-mobilehub-687604833-Announcements"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_creationDate"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_creationDate" : "creationDate",
               "_announcementId" : "announcementId",
               "_category" : "category",
               "_content" : "content",
               "_keywords" : "keywords",
               "_title" : "title",
        ]
    }
}
