//
//  Sermons.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.10
//

import Foundation
import UIKit
import AWSDynamoDB

class Sermons: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _creationDate: NSNumber?
    var _keywords: Set<String>?
    var _sermon: String?
    var _sermonId: String?
    var _title: String?
    var _verse: String?
    
    class func dynamoDBTableName() -> String {

        return "joyfulchurch-mobilehub-687604833-Sermons"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_creationDate"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_creationDate" : "creationDate",
               "_keywords" : "keywords",
               "_sermon" : "sermon",
               "_sermonId" : "sermonId",
               "_title" : "title",
               "_verse" : "verse",
        ]
    }
}
